// Copyright (c) 2026 GameSir Labs and contributors
// SPDX-License-Identifier: LGPL-2.1-or-later
#pragma once

#include "DXILParser/DXILParser.hpp"

namespace dxmt::dxil {

// Reduced from DXC's generated CoreOps metadata table. Keep this independent
// from DXC/LLVM so opcode semantics remain available in cross builds.
constexpr DxilOpcodeInfo kDxilOpcodeInfos[] = {
    {0u, "TempRegLoad", "TempRegLoad", "Temporary, indexable, input, output registers", "ro", "hfwi", 6u, 0u, 0x0u, false},
    {1u, "TempRegStore", "TempRegStore", "Temporary, indexable, input, output registers", "", "hfwi", 6u, 0u, 0x0u, false},
    {2u, "MinPrecXRegLoad", "MinPrecXRegLoad", "Temporary, indexable, input, output registers", "ro", "hw", 6u, 0u, 0x0u, false},
    {3u, "MinPrecXRegStore", "MinPrecXRegStore", "Temporary, indexable, input, output registers", "", "hw", 6u, 0u, 0x0u, false},
    {4u, "LoadInput", "LoadInput", "Temporary, indexable, input, output registers", "rn", "hfwi", 6u, 0u, 0x0u, false},
    {5u, "StoreOutput", "StoreOutput", "Temporary, indexable, input, output registers", "", "hfwi", 6u, 0u, 0x0u, false},
    {6u, "FAbs", "Unary", "Unary float", "rn", "hfd<hfd", 6u, 0u, 0x0u, false},
    {7u, "Saturate", "Unary", "Unary float", "rn", "hfd<hfd", 6u, 0u, 0x0u, false},
    {8u, "IsNaN", "IsSpecialFloat", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {9u, "IsInf", "IsSpecialFloat", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {10u, "IsFinite", "IsSpecialFloat", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {11u, "IsNormal", "IsSpecialFloat", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {12u, "Cos", "Unary", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {13u, "Sin", "Unary", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {14u, "Tan", "Unary", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {15u, "Acos", "Unary", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {16u, "Asin", "Unary", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {17u, "Atan", "Unary", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {18u, "Hcos", "Unary", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {19u, "Hsin", "Unary", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {20u, "Htan", "Unary", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {21u, "Exp", "Unary", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {22u, "Frc", "Unary", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {23u, "Log", "Unary", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {24u, "Sqrt", "Unary", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {25u, "Rsqrt", "Unary", "Unary float", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {26u, "Round_ne", "Unary", "Unary float - rounding", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {27u, "Round_ni", "Unary", "Unary float - rounding", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {28u, "Round_pi", "Unary", "Unary float - rounding", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {29u, "Round_z", "Unary", "Unary float - rounding", "rn", "hf<hf", 6u, 0u, 0x0u, false},
    {30u, "Bfrev", "Unary", "Unary int", "rn", "wil<wil", 6u, 0u, 0x0u, false},
    {31u, "Countbits", "UnaryBits", "Unary int", "rn", "wil<wil", 6u, 0u, 0x0u, false},
    {32u, "FirstbitLo", "UnaryBits", "Unary int", "rn", "wil<wil", 6u, 0u, 0x0u, false},
    {33u, "FirstbitHi", "UnaryBits", "Unary uint", "rn", "wil<wil", 6u, 0u, 0x0u, false},
    {34u, "FirstbitSHi", "UnaryBits", "Unary int", "rn", "wil<wil", 6u, 0u, 0x0u, false},
    {35u, "FMax", "Binary", "Binary float", "rn", "hfd<hfd", 6u, 0u, 0x0u, false},
    {36u, "FMin", "Binary", "Binary float", "rn", "hfd<hfd", 6u, 0u, 0x0u, false},
    {37u, "IMax", "Binary", "Binary int", "rn", "wil<wil", 6u, 0u, 0x0u, false},
    {38u, "IMin", "Binary", "Binary int", "rn", "wil<wil", 6u, 0u, 0x0u, false},
    {39u, "UMax", "Binary", "Binary uint", "rn", "wil<wil", 6u, 0u, 0x0u, false},
    {40u, "UMin", "Binary", "Binary uint", "rn", "wil<wil", 6u, 0u, 0x0u, false},
    {41u, "IMul", "BinaryWithTwoOuts", "Binary int with two outputs", "rn", "i", 6u, 0u, 0x0u, false},
    {42u, "UMul", "BinaryWithTwoOuts", "Binary uint with two outputs", "rn", "i", 6u, 0u, 0x0u, false},
    {43u, "UDiv", "BinaryWithTwoOuts", "Binary uint with two outputs", "rn", "i", 6u, 0u, 0x0u, false},
    {44u, "UAddc", "BinaryWithCarryOrBorrow", "Binary uint with carry or borrow", "rn", "i", 6u, 0u, 0x0u, false},
    {45u, "USubb", "BinaryWithCarryOrBorrow", "Binary uint with carry or borrow", "rn", "i", 6u, 0u, 0x0u, false},
    {46u, "FMad", "Tertiary", "Tertiary float", "rn", "hfd<hfd", 6u, 0u, 0x0u, false},
    {47u, "Fma", "Tertiary", "Tertiary float", "rn", "d<d", 6u, 0u, 0x0u, false},
    {48u, "IMad", "Tertiary", "Tertiary int", "rn", "wil<wil", 6u, 0u, 0x0u, false},
    {49u, "UMad", "Tertiary", "Tertiary uint", "rn", "wil<wil", 6u, 0u, 0x0u, false},
    {50u, "Msad", "Tertiary", "Tertiary int", "rn", "i", 6u, 0u, 0x0u, false},
    {51u, "Ibfe", "Tertiary", "Tertiary int", "rn", "i", 6u, 0u, 0x0u, false},
    {52u, "Ubfe", "Tertiary", "Tertiary uint", "rn", "i", 6u, 0u, 0x0u, false},
    {53u, "Bfi", "Quaternary", "Quaternary", "rn", "i", 6u, 0u, 0x0u, false},
    {54u, "Dot2", "Dot2", "Dot", "rn", "hf", 6u, 0u, 0x0u, false},
    {55u, "Dot3", "Dot3", "Dot", "rn", "hf", 6u, 0u, 0x0u, false},
    {56u, "Dot4", "Dot4", "Dot", "rn", "hf", 6u, 0u, 0x0u, false},
    {57u, "CreateHandle", "CreateHandle", "Resources", "ro", "v", 6u, 0u, 0x0u, false},
    {58u, "CBufferLoad", "CBufferLoad", "Resources", "ro", "hfd8wil", 6u, 0u, 0x0u, false},
    {59u, "CBufferLoadLegacy", "CBufferLoadLegacy", "Resources", "ro", "hfdwil", 6u, 0u, 0x0u, false},
    {60u, "Sample", "Sample", "Resources - sample", "ro", "hfwi", 6u, 0u, 0x2u, false},
    {61u, "SampleBias", "SampleBias", "Resources - sample", "ro", "hfwi", 6u, 0u, 0x2u, false},
    {62u, "SampleLevel", "SampleLevel", "Resources - sample", "ro", "hfwi", 6u, 0u, 0x0u, false},
    {63u, "SampleGrad", "SampleGrad", "Resources - sample", "ro", "hfwi", 6u, 0u, 0x0u, false},
    {64u, "SampleCmp", "SampleCmp", "Resources - sample", "ro", "hf", 6u, 0u, 0x2u, false},
    {65u, "SampleCmpLevelZero", "SampleCmpLevelZero", "Resources - sample", "ro", "hf", 6u, 0u, 0x0u, false},
    {66u, "TextureLoad", "TextureLoad", "Resources", "ro", "hfwi", 6u, 0u, 0x0u, false},
    {67u, "TextureStore", "TextureStore", "Resources", "", "hfwi", 6u, 0u, 0x0u, false},
    {68u, "BufferLoad", "BufferLoad", "Resources", "ro", "hfwi", 6u, 0u, 0x0u, false},
    {69u, "BufferStore", "BufferStore", "Resources", "", "hfwi", 6u, 0u, 0x0u, false},
    {70u, "BufferUpdateCounter", "BufferUpdateCounter", "Resources", "", "v", 6u, 0u, 0x0u, false},
    {71u, "CheckAccessFullyMapped", "CheckAccessFullyMapped", "Resources", "ro", "i", 6u, 0u, 0x0u, false},
    {72u, "GetDimensions", "GetDimensions", "Resources", "ro", "v", 6u, 0u, 0x0u, false},
    {73u, "TextureGather", "TextureGather", "Resources - gather", "ro", "hfwi", 6u, 0u, 0x0u, false},
    {74u, "TextureGatherCmp", "TextureGatherCmp", "Resources - gather", "ro", "hfwi", 6u, 0u, 0x0u, false},
    {75u, "Texture2DMSGetSamplePosition", "Texture2DMSGetSamplePosition", "Resources - sample", "ro", "v", 6u, 0u, 0x0u, false},
    {76u, "RenderTargetGetSamplePosition", "RenderTargetGetSamplePosition", "Resources - sample", "ro", "v", 6u, 0u, 0x0u, false},
    {77u, "RenderTargetGetSampleCount", "RenderTargetGetSampleCount", "Resources - sample", "ro", "v", 6u, 0u, 0x0u, false},
    {78u, "AtomicBinOp", "AtomicBinOp", "Synchronization", "", "li", 6u, 0u, 0x0u, false},
    {79u, "AtomicCompareExchange", "AtomicCompareExchange", "Synchronization", "", "li", 6u, 0u, 0x0u, false},
    {80u, "Barrier", "Barrier", "Synchronization", "nd", "v", 6u, 0u, 0x20u, false},
    {81u, "CalculateLOD", "CalculateLOD", "Derivatives", "ro", "f", 6u, 0u, 0x2u, false},
    {82u, "Discard", "Discard", "Pixel shader", "", "v", 6u, 0u, 0x0u, false},
    {83u, "DerivCoarseX", "Unary", "Derivatives", "rn", "hf<hf", 6u, 0u, 0x3u, false},
    {84u, "DerivCoarseY", "Unary", "Derivatives", "rn", "hf<hf", 6u, 0u, 0x3u, false},
    {85u, "DerivFineX", "Unary", "Derivatives", "rn", "hf<hf", 6u, 0u, 0x3u, false},
    {86u, "DerivFineY", "Unary", "Derivatives", "rn", "hf<hf", 6u, 0u, 0x3u, false},
    {87u, "EvalSnapped", "EvalSnapped", "Pixel shader", "rn", "hf", 6u, 0u, 0x0u, false},
    {88u, "EvalSampleIndex", "EvalSampleIndex", "Pixel shader", "rn", "hf", 6u, 0u, 0x0u, false},
    {89u, "EvalCentroid", "EvalCentroid", "Pixel shader", "rn", "hf", 6u, 0u, 0x0u, false},
    {90u, "SampleIndex", "SampleIndex", "Pixel shader", "rn", "i", 6u, 0u, 0x0u, false},
    {91u, "Coverage", "Coverage", "Pixel shader", "rn", "i", 6u, 0u, 0x0u, false},
    {92u, "InnerCoverage", "InnerCoverage", "Pixel shader", "rn", "i", 6u, 0u, 0x0u, false},
    {93u, "ThreadId", "ThreadId", "Compute/Mesh/Amplification/Node shader", "rn", "i", 6u, 0u, 0x0u, false},
    {94u, "GroupId", "GroupId", "Compute/Mesh/Amplification/Node shader", "rn", "i", 6u, 0u, 0x0u, false},
    {95u, "ThreadIdInGroup", "ThreadIdInGroup", "Compute/Mesh/Amplification/Node shader", "rn", "i", 6u, 0u, 0x0u, false},
    {96u, "FlattenedThreadIdInGroup", "FlattenedThreadIdInGroup", "Compute/Mesh/Amplification/Node shader", "rn", "i", 6u, 0u, 0x0u, false},
    {97u, "EmitStream", "EmitStream", "Geometry shader", "", "v", 6u, 0u, 0x0u, false},
    {98u, "CutStream", "CutStream", "Geometry shader", "", "v", 6u, 0u, 0x0u, false},
    {99u, "EmitThenCutStream", "EmitThenCutStream", "Geometry shader", "", "v", 6u, 0u, 0x0u, false},
    {100u, "GSInstanceID", "GSInstanceID", "Geometry shader", "rn", "i", 6u, 0u, 0x0u, false},
    {101u, "MakeDouble", "MakeDouble", "Double precision", "rn", "d", 6u, 0u, 0x0u, false},
    {102u, "SplitDouble", "SplitDouble", "Double precision", "rn", "d", 6u, 0u, 0x0u, false},
    {103u, "LoadOutputControlPoint", "LoadOutputControlPoint", "Domain and hull shader", "rn", "hfwi", 6u, 0u, 0x0u, false},
    {104u, "LoadPatchConstant", "LoadPatchConstant", "Domain and hull shader", "rn", "hfwi", 6u, 0u, 0x0u, false},
    {105u, "DomainLocation", "DomainLocation", "Domain shader", "rn", "f", 6u, 0u, 0x0u, false},
    {106u, "StorePatchConstant", "StorePatchConstant", "Hull shader", "", "hfwi", 6u, 0u, 0x0u, false},
    {107u, "OutputControlPointID", "OutputControlPointID", "Hull shader", "rn", "i", 6u, 0u, 0x0u, false},
    {108u, "PrimitiveID", "PrimitiveID", "Hull, Domain and Geometry shaders", "rn", "i", 6u, 0u, 0x0u, false},
    {109u, "CycleCounterLegacy", "CycleCounterLegacy", "Other", "", "v", 6u, 0u, 0x0u, false},
    {110u, "WaveIsFirstLane", "WaveIsFirstLane", "Wave", "", "v", 6u, 0u, 0x8u, false},
    {111u, "WaveGetLaneIndex", "WaveGetLaneIndex", "Wave", "ro", "v", 6u, 0u, 0x8u, false},
    {112u, "WaveGetLaneCount", "WaveGetLaneCount", "Wave", "rn", "v", 6u, 0u, 0x8u, false},
    {113u, "WaveAnyTrue", "WaveAnyTrue", "Wave", "", "v", 6u, 0u, 0x8u, false},
    {114u, "WaveAllTrue", "WaveAllTrue", "Wave", "", "v", 6u, 0u, 0x8u, false},
    {115u, "WaveActiveAllEqual", "WaveActiveAllEqual", "Wave", "", "hfd18wil<hfd18wil", 6u, 0u, 0x8u, false},
    {116u, "WaveActiveBallot", "WaveActiveBallot", "Wave", "", "v", 6u, 0u, 0x8u, false},
    {117u, "WaveReadLaneAt", "WaveReadLaneAt", "Wave", "", "hfd18wil<hfd18wil", 6u, 0u, 0x8u, false},
    {118u, "WaveReadLaneFirst", "WaveReadLaneFirst", "Wave", "", "hfd18wil<hfd18wil", 6u, 0u, 0x8u, false},
    {119u, "WaveActiveOp", "WaveActiveOp", "Wave", "", "hfd18wil<hfd18wil", 6u, 0u, 0x8u, false},
    {120u, "WaveActiveBit", "WaveActiveBit", "Wave", "", "8wil<8wil", 6u, 0u, 0x8u, false},
    {121u, "WavePrefixOp", "WavePrefixOp", "Wave", "", "hfd8wil<hfd8wil", 6u, 0u, 0x8u, false},
    {122u, "QuadReadLaneAt", "QuadReadLaneAt", "Quad Wave Ops", "", "hfd18wil<hfd18wil", 6u, 0u, 0x8u, false},
    {123u, "QuadOp", "QuadOp", "Quad Wave Ops", "", "hfd8wil<hfd8wil", 6u, 0u, 0x8u, false},
    {124u, "BitcastI16toF16", "BitcastI16toF16", "Bitcasts with different sizes", "rn", "v", 6u, 0u, 0x0u, false},
    {125u, "BitcastF16toI16", "BitcastF16toI16", "Bitcasts with different sizes", "rn", "v", 6u, 0u, 0x0u, false},
    {126u, "BitcastI32toF32", "BitcastI32toF32", "Bitcasts with different sizes", "rn", "v", 6u, 0u, 0x0u, false},
    {127u, "BitcastF32toI32", "BitcastF32toI32", "Bitcasts with different sizes", "rn", "v", 6u, 0u, 0x0u, false},
    {128u, "BitcastI64toF64", "BitcastI64toF64", "Bitcasts with different sizes", "rn", "v", 6u, 0u, 0x0u, false},
    {129u, "BitcastF64toI64", "BitcastF64toI64", "Bitcasts with different sizes", "rn", "v", 6u, 0u, 0x0u, false},
    {130u, "LegacyF32ToF16", "LegacyF32ToF16", "Legacy floating-point", "rn", "v", 6u, 0u, 0x0u, false},
    {131u, "LegacyF16ToF32", "LegacyF16ToF32", "Legacy floating-point", "rn", "v", 6u, 0u, 0x0u, false},
    {132u, "LegacyDoubleToFloat", "LegacyDoubleToFloat", "Double precision", "rn", "v", 6u, 0u, 0x0u, false},
    {133u, "LegacyDoubleToSInt32", "LegacyDoubleToSInt32", "Double precision", "rn", "v", 6u, 0u, 0x0u, false},
    {134u, "LegacyDoubleToUInt32", "LegacyDoubleToUInt32", "Double precision", "rn", "v", 6u, 0u, 0x0u, false},
    {135u, "WaveAllBitCount", "WaveAllOp", "Wave", "", "v", 6u, 0u, 0x8u, false},
    {136u, "WavePrefixBitCount", "WavePrefixOp", "Wave", "", "v", 6u, 0u, 0x8u, false},
    {137u, "AttributeAtVertex", "AttributeAtVertex", "Pixel shader", "rn", "hfiw", 6u, 1u, 0x0u, false},
    {138u, "ViewID", "ViewID", "Graphics shader", "rn", "i", 6u, 1u, 0x0u, false},
    {139u, "RawBufferLoad", "RawBufferLoad", "Resources", "ro", "hfwidl", 6u, 2u, 0x0u, false},
    {140u, "RawBufferStore", "RawBufferStore", "Resources", "", "hfwidl", 6u, 2u, 0x0u, false},
    {141u, "InstanceID", "InstanceID", "Raytracing object space uint System Values", "rn", "i", 6u, 3u, 0x0u, false},
    {142u, "InstanceIndex", "InstanceIndex", "Raytracing object space uint System Values", "rn", "i", 6u, 3u, 0x0u, false},
    {143u, "HitKind", "HitKind", "Raytracing hit uint System Values", "rn", "i", 6u, 3u, 0x0u, false},
    {144u, "RayFlags", "RayFlags", "Raytracing uint System Values", "rn", "i", 6u, 3u, 0x0u, false},
    {145u, "DispatchRaysIndex", "DispatchRaysIndex", "Ray Dispatch Arguments", "rn", "i", 6u, 3u, 0x0u, false},
    {146u, "DispatchRaysDimensions", "DispatchRaysDimensions", "Ray Dispatch Arguments", "rn", "i", 6u, 3u, 0x0u, false},
    {147u, "WorldRayOrigin", "WorldRayOrigin", "Ray Vectors", "rn", "f", 6u, 3u, 0x0u, false},
    {148u, "WorldRayDirection", "WorldRayDirection", "Ray Vectors", "rn", "f", 6u, 3u, 0x0u, false},
    {149u, "ObjectRayOrigin", "ObjectRayOrigin", "Ray object space Vectors", "rn", "f", 6u, 3u, 0x0u, false},
    {150u, "ObjectRayDirection", "ObjectRayDirection", "Ray object space Vectors", "rn", "f", 6u, 3u, 0x0u, false},
    {151u, "ObjectToWorld", "ObjectToWorld", "Ray Transforms", "rn", "f", 6u, 3u, 0x0u, false},
    {152u, "WorldToObject", "WorldToObject", "Ray Transforms", "rn", "f", 6u, 3u, 0x0u, false},
    {153u, "RayTMin", "RayTMin", "RayT", "rn", "f", 6u, 3u, 0x0u, false},
    {154u, "RayTCurrent", "RayTCurrent", "RayT", "ro", "f", 6u, 3u, 0x0u, false},
    {155u, "IgnoreHit", "IgnoreHit", "AnyHit Terminals", "nr", "v", 6u, 3u, 0x0u, false},
    {156u, "AcceptHitAndEndSearch", "AcceptHitAndEndSearch", "AnyHit Terminals", "nr", "v", 6u, 3u, 0x0u, false},
    {157u, "TraceRay", "TraceRay", "Indirect Shader Invocation", "", "u", 6u, 3u, 0x0u, false},
    {158u, "ReportHit", "ReportHit", "Indirect Shader Invocation", "", "u", 6u, 3u, 0x0u, false},
    {159u, "CallShader", "CallShader", "Indirect Shader Invocation", "", "u", 6u, 3u, 0x0u, false},
    {160u, "CreateHandleForLib", "CreateHandleForLib", "Library create handle from resource struct (like HL intrinsic)", "ro", "o", 6u, 3u, 0x0u, false},
    {161u, "PrimitiveIndex", "PrimitiveIndex", "Raytracing object space uint System Values", "rn", "i", 6u, 3u, 0x0u, false},
    {162u, "Dot2AddHalf", "Dot2AddHalf", "Dot product with accumulate", "rn", "f", 6u, 4u, 0x0u, false},
    {163u, "Dot4AddI8Packed", "Dot4AddPacked", "Dot product with accumulate", "rn", "i", 6u, 4u, 0x0u, false},
    {164u, "Dot4AddU8Packed", "Dot4AddPacked", "Dot product with accumulate", "rn", "i", 6u, 4u, 0x0u, false},
    {165u, "WaveMatch", "WaveMatch", "Wave", "", "hfd8wil<hfd8wil", 6u, 5u, 0x8u, false},
    {166u, "WaveMultiPrefixOp", "WaveMultiPrefixOp", "Wave", "", "hfd8wil<hfd8wil", 6u, 5u, 0x8u, false},
    {167u, "WaveMultiPrefixBitCount", "WaveMultiPrefixBitCount", "Wave", "", "v", 6u, 5u, 0x8u, false},
    {168u, "SetMeshOutputCounts", "SetMeshOutputCounts", "Mesh shader instructions", "", "v", 6u, 5u, 0x0u, false},
    {169u, "EmitIndices", "EmitIndices", "Mesh shader instructions", "", "v", 6u, 5u, 0x0u, false},
    {170u, "GetMeshPayload", "GetMeshPayload", "Mesh shader instructions", "ro", "u", 6u, 5u, 0x0u, false},
    {171u, "StoreVertexOutput", "StoreVertexOutput", "Mesh shader instructions", "", "hfwi", 6u, 5u, 0x0u, false},
    {172u, "StorePrimitiveOutput", "StorePrimitiveOutput", "Mesh shader instructions", "", "hfwi", 6u, 5u, 0x0u, false},
    {173u, "DispatchMesh", "DispatchMesh", "Amplification shader instructions", "", "u", 6u, 5u, 0x0u, false},
    {174u, "WriteSamplerFeedback", "WriteSamplerFeedback", "Sampler Feedback", "", "v", 6u, 5u, 0x6u, false},
    {175u, "WriteSamplerFeedbackBias", "WriteSamplerFeedbackBias", "Sampler Feedback", "", "v", 6u, 5u, 0x6u, false},
    {176u, "WriteSamplerFeedbackLevel", "WriteSamplerFeedbackLevel", "Sampler Feedback", "", "v", 6u, 5u, 0x4u, false},
    {177u, "WriteSamplerFeedbackGrad", "WriteSamplerFeedbackGrad", "Sampler Feedback", "", "v", 6u, 5u, 0x4u, false},
    {178u, "AllocateRayQuery", "AllocateRayQuery", "Inline Ray Query", "", "v", 6u, 5u, 0x0u, false},
    {179u, "RayQuery_TraceRayInline", "RayQuery_TraceRayInline", "Inline Ray Query", "", "v", 6u, 5u, 0x0u, false},
    {180u, "RayQuery_Proceed", "RayQuery_Proceed", "Inline Ray Query", "", "1", 6u, 5u, 0x0u, false},
    {181u, "RayQuery_Abort", "RayQuery_Abort", "Inline Ray Query", "", "v", 6u, 5u, 0x0u, false},
    {182u, "RayQuery_CommitNonOpaqueTriangleHit", "RayQuery_CommitNonOpaqueTriangleHit", "Inline Ray Query", "", "v", 6u, 5u, 0x0u, false},
    {183u, "RayQuery_CommitProceduralPrimitiveHit", "RayQuery_CommitProceduralPrimitiveHit", "Inline Ray Query", "", "v", 6u, 5u, 0x0u, false},
    {184u, "RayQuery_CommittedStatus", "RayQuery_StateScalar", "Inline Ray Query", "ro", "i", 6u, 5u, 0x0u, false},
    {185u, "RayQuery_CandidateType", "RayQuery_StateScalar", "Inline Ray Query", "ro", "i", 6u, 5u, 0x0u, false},
    {186u, "RayQuery_CandidateObjectToWorld3x4", "RayQuery_StateMatrix", "Inline Ray Query", "ro", "f", 6u, 5u, 0x0u, false},
    {187u, "RayQuery_CandidateWorldToObject3x4", "RayQuery_StateMatrix", "Inline Ray Query", "ro", "f", 6u, 5u, 0x0u, false},
    {188u, "RayQuery_CommittedObjectToWorld3x4", "RayQuery_StateMatrix", "Inline Ray Query", "ro", "f", 6u, 5u, 0x0u, false},
    {189u, "RayQuery_CommittedWorldToObject3x4", "RayQuery_StateMatrix", "Inline Ray Query", "ro", "f", 6u, 5u, 0x0u, false},
    {190u, "RayQuery_CandidateProceduralPrimitiveNonOpaque", "RayQuery_StateScalar", "Inline Ray Query", "ro", "1", 6u, 5u, 0x0u, false},
    {191u, "RayQuery_CandidateTriangleFrontFace", "RayQuery_StateScalar", "Inline Ray Query", "ro", "1", 6u, 5u, 0x0u, false},
    {192u, "RayQuery_CommittedTriangleFrontFace", "RayQuery_StateScalar", "Inline Ray Query", "ro", "1", 6u, 5u, 0x0u, false},
    {193u, "RayQuery_CandidateTriangleBarycentrics", "RayQuery_StateVector", "Inline Ray Query", "ro", "f", 6u, 5u, 0x0u, false},
    {194u, "RayQuery_CommittedTriangleBarycentrics", "RayQuery_StateVector", "Inline Ray Query", "ro", "f", 6u, 5u, 0x0u, false},
    {195u, "RayQuery_RayFlags", "RayQuery_StateScalar", "Inline Ray Query", "ro", "i", 6u, 5u, 0x0u, false},
    {196u, "RayQuery_WorldRayOrigin", "RayQuery_StateVector", "Inline Ray Query", "ro", "f", 6u, 5u, 0x0u, false},
    {197u, "RayQuery_WorldRayDirection", "RayQuery_StateVector", "Inline Ray Query", "ro", "f", 6u, 5u, 0x0u, false},
    {198u, "RayQuery_RayTMin", "RayQuery_StateScalar", "Inline Ray Query", "ro", "f", 6u, 5u, 0x0u, false},
    {199u, "RayQuery_CandidateTriangleRayT", "RayQuery_StateScalar", "Inline Ray Query", "ro", "f", 6u, 5u, 0x0u, false},
    {200u, "RayQuery_CommittedRayT", "RayQuery_StateScalar", "Inline Ray Query", "ro", "f", 6u, 5u, 0x0u, false},
    {201u, "RayQuery_CandidateInstanceIndex", "RayQuery_StateScalar", "Inline Ray Query", "ro", "i", 6u, 5u, 0x0u, false},
    {202u, "RayQuery_CandidateInstanceID", "RayQuery_StateScalar", "Inline Ray Query", "ro", "i", 6u, 5u, 0x0u, false},
    {203u, "RayQuery_CandidateGeometryIndex", "RayQuery_StateScalar", "Inline Ray Query", "ro", "i", 6u, 5u, 0x0u, false},
    {204u, "RayQuery_CandidatePrimitiveIndex", "RayQuery_StateScalar", "Inline Ray Query", "ro", "i", 6u, 5u, 0x0u, false},
    {205u, "RayQuery_CandidateObjectRayOrigin", "RayQuery_StateVector", "Inline Ray Query", "ro", "f", 6u, 5u, 0x0u, false},
    {206u, "RayQuery_CandidateObjectRayDirection", "RayQuery_StateVector", "Inline Ray Query", "ro", "f", 6u, 5u, 0x0u, false},
    {207u, "RayQuery_CommittedInstanceIndex", "RayQuery_StateScalar", "Inline Ray Query", "ro", "i", 6u, 5u, 0x0u, false},
    {208u, "RayQuery_CommittedInstanceID", "RayQuery_StateScalar", "Inline Ray Query", "ro", "i", 6u, 5u, 0x0u, false},
    {209u, "RayQuery_CommittedGeometryIndex", "RayQuery_StateScalar", "Inline Ray Query", "ro", "i", 6u, 5u, 0x0u, false},
    {210u, "RayQuery_CommittedPrimitiveIndex", "RayQuery_StateScalar", "Inline Ray Query", "ro", "i", 6u, 5u, 0x0u, false},
    {211u, "RayQuery_CommittedObjectRayOrigin", "RayQuery_StateVector", "Inline Ray Query", "ro", "f", 6u, 5u, 0x0u, false},
    {212u, "RayQuery_CommittedObjectRayDirection", "RayQuery_StateVector", "Inline Ray Query", "ro", "f", 6u, 5u, 0x0u, false},
    {213u, "GeometryIndex", "GeometryIndex", "Raytracing object space uint System Values, raytracing tier 1.1", "rn", "i", 6u, 5u, 0x0u, false},
    {214u, "RayQuery_CandidateInstanceContributionToHitGroupIndex", "RayQuery_StateScalar", "Inline Ray Query", "ro", "i", 6u, 5u, 0x0u, false},
    {215u, "RayQuery_CommittedInstanceContributionToHitGroupIndex", "RayQuery_StateScalar", "Inline Ray Query", "ro", "i", 6u, 5u, 0x0u, false},
    {216u, "AnnotateHandle", "AnnotateHandle", "Get handle from heap", "rn", "v", 6u, 6u, 0x0u, false},
    {217u, "CreateHandleFromBinding", "CreateHandleFromBinding", "Get handle from heap", "rn", "v", 6u, 6u, 0x0u, false},
    {218u, "CreateHandleFromHeap", "CreateHandleFromHeap", "Get handle from heap", "rn", "v", 6u, 6u, 0x0u, false},
    {219u, "Unpack4x8", "Unpack4x8", "Unpacking intrinsics", "rn", "iw", 6u, 6u, 0x0u, false},
    {220u, "Pack4x8", "Pack4x8", "Packing intrinsics", "rn", "iw", 6u, 6u, 0x0u, false},
    {221u, "IsHelperLane", "IsHelperLane", "Helper Lanes", "ro", "1", 6u, 6u, 0x0u, false},
    {222u, "QuadVote", "QuadVote", "Quad Wave Ops", "", "1", 6u, 7u, 0x8u, false},
    {223u, "TextureGatherRaw", "TextureGatherRaw", "Resources - gather", "ro", "wil", 6u, 7u, 0x0u, false},
    {224u, "SampleCmpLevel", "SampleCmpLevel", "Resources - sample", "ro", "hf", 6u, 7u, 0x0u, false},
    {225u, "TextureStoreSample", "TextureStoreSample", "Resources", "", "hfwi", 6u, 7u, 0x0u, false},
    {226u, "Reserved0", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {227u, "Reserved1", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {228u, "Reserved2", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {229u, "Reserved3", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {230u, "Reserved4", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {231u, "Reserved5", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {232u, "Reserved6", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {233u, "Reserved7", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {234u, "Reserved8", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {235u, "Reserved9", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {236u, "Reserved10", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {237u, "Reserved11", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {238u, "AllocateNodeOutputRecords", "AllocateNodeOutputRecords", "Create/Annotate Node Handles", "", "v", 6u, 8u, 0x0u, false},
    {239u, "GetNodeRecordPtr", "GetNodeRecordPtr", "Get Pointer to Node Record in Address Space 6", "rn", "u", 6u, 8u, 0x0u, false},
    {240u, "IncrementOutputCount", "IncrementOutputCount", "Work Graph intrinsics", "", "v", 6u, 8u, 0x0u, false},
    {241u, "OutputComplete", "OutputComplete", "Work Graph intrinsics", "", "v", 6u, 8u, 0x0u, false},
    {242u, "GetInputRecordCount", "GetInputRecordCount", "Work Graph intrinsics", "ro", "v", 6u, 8u, 0x0u, false},
    {243u, "FinishedCrossGroupSharing", "FinishedCrossGroupSharing", "Work Graph intrinsics", "", "v", 6u, 8u, 0x0u, false},
    {244u, "BarrierByMemoryType", "BarrierByMemoryType", "Synchronization", "nd", "v", 6u, 8u, 0x20u, false},
    {245u, "BarrierByMemoryHandle", "BarrierByMemoryHandle", "Synchronization", "nd", "v", 6u, 8u, 0x20u, false},
    {246u, "BarrierByNodeRecordHandle", "BarrierByNodeRecordHandle", "Synchronization", "nd", "v", 6u, 8u, 0x20u, false},
    {247u, "CreateNodeOutputHandle", "createNodeOutputHandle", "Create/Annotate Node Handles", "rn", "v", 6u, 8u, 0x0u, false},
    {248u, "IndexNodeHandle", "IndexNodeHandle", "Create/Annotate Node Handles", "rn", "v", 6u, 8u, 0x0u, false},
    {249u, "AnnotateNodeHandle", "AnnotateNodeHandle", "Create/Annotate Node Handles", "rn", "v", 6u, 8u, 0x0u, false},
    {250u, "CreateNodeInputRecordHandle", "CreateNodeInputRecordHandle", "Create/Annotate Node Handles", "rn", "v", 6u, 8u, 0x0u, false},
    {251u, "AnnotateNodeRecordHandle", "AnnotateNodeRecordHandle", "Create/Annotate Node Handles", "rn", "v", 6u, 8u, 0x0u, false},
    {252u, "NodeOutputIsValid", "NodeOutputIsValid", "Work Graph intrinsics", "ro", "v", 6u, 8u, 0x0u, false},
    {253u, "GetRemainingRecursionLevels", "GetRemainingRecursionLevels", "Work Graph intrinsics", "ro", "v", 6u, 8u, 0x0u, false},
    {254u, "SampleCmpGrad", "SampleCmpGrad", "Comparison Samples", "ro", "hf", 6u, 8u, 0x0u, false},
    {255u, "SampleCmpBias", "SampleCmpBias", "Comparison Samples", "ro", "hf", 6u, 8u, 0x2u, false},
    {256u, "StartVertexLocation", "StartVertexLocation", "Extended Command Information", "rn", "i", 6u, 8u, 0x0u, false},
    {257u, "StartInstanceLocation", "StartInstanceLocation", "Extended Command Information", "rn", "i", 6u, 8u, 0x0u, false},
    {258u, "AllocateRayQuery2", "AllocateRayQuery2", "Inline Ray Query", "", "v", 6u, 9u, 0x0u, false},
    {259u, "ReservedA0", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {260u, "ReservedA1", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {261u, "ReservedA2", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {262u, "HitObject_TraceRay", "HitObject_TraceRay", "Shader Execution Reordering", "", "u", 6u, 9u, 0x0u, false},
    {263u, "HitObject_FromRayQuery", "HitObject_FromRayQuery", "Shader Execution Reordering", "ro", "v", 6u, 9u, 0x0u, false},
    {264u, "HitObject_FromRayQueryWithAttrs", "HitObject_FromRayQueryWithAttrs", "Shader Execution Reordering", "ro", "u", 6u, 9u, 0x0u, false},
    {265u, "HitObject_MakeMiss", "HitObject_MakeMiss", "Shader Execution Reordering", "rn", "v", 6u, 9u, 0x0u, false},
    {266u, "HitObject_MakeNop", "HitObject_MakeNop", "Shader Execution Reordering", "rn", "v", 6u, 9u, 0x0u, false},
    {267u, "HitObject_Invoke", "HitObject_Invoke", "Shader Execution Reordering", "", "u", 6u, 9u, 0x0u, false},
    {268u, "MaybeReorderThread", "MaybeReorderThread", "Shader Execution Reordering", "", "v", 6u, 9u, 0x0u, false},
    {269u, "HitObject_IsMiss", "HitObject_StateScalar", "Shader Execution Reordering", "rn", "1", 6u, 9u, 0x0u, false},
    {270u, "HitObject_IsHit", "HitObject_StateScalar", "Shader Execution Reordering", "rn", "1", 6u, 9u, 0x0u, false},
    {271u, "HitObject_IsNop", "HitObject_StateScalar", "Shader Execution Reordering", "rn", "1", 6u, 9u, 0x0u, false},
    {272u, "HitObject_RayFlags", "HitObject_StateScalar", "Shader Execution Reordering", "rn", "i", 6u, 9u, 0x0u, false},
    {273u, "HitObject_RayTMin", "HitObject_StateScalar", "Shader Execution Reordering", "rn", "f", 6u, 9u, 0x0u, false},
    {274u, "HitObject_RayTCurrent", "HitObject_StateScalar", "Shader Execution Reordering", "rn", "f", 6u, 9u, 0x0u, false},
    {275u, "HitObject_WorldRayOrigin", "HitObject_StateVector", "Shader Execution Reordering", "rn", "f", 6u, 9u, 0x0u, false},
    {276u, "HitObject_WorldRayDirection", "HitObject_StateVector", "Shader Execution Reordering", "rn", "f", 6u, 9u, 0x0u, false},
    {277u, "HitObject_ObjectRayOrigin", "HitObject_StateVector", "Shader Execution Reordering", "rn", "f", 6u, 9u, 0x0u, false},
    {278u, "HitObject_ObjectRayDirection", "HitObject_StateVector", "Shader Execution Reordering", "rn", "f", 6u, 9u, 0x0u, false},
    {279u, "HitObject_ObjectToWorld3x4", "HitObject_StateMatrix", "Shader Execution Reordering", "rn", "f", 6u, 9u, 0x0u, false},
    {280u, "HitObject_WorldToObject3x4", "HitObject_StateMatrix", "Shader Execution Reordering", "rn", "f", 6u, 9u, 0x0u, false},
    {281u, "HitObject_GeometryIndex", "HitObject_StateScalar", "Shader Execution Reordering", "rn", "i", 6u, 9u, 0x0u, false},
    {282u, "HitObject_InstanceIndex", "HitObject_StateScalar", "Shader Execution Reordering", "rn", "i", 6u, 9u, 0x0u, false},
    {283u, "HitObject_InstanceID", "HitObject_StateScalar", "Shader Execution Reordering", "rn", "i", 6u, 9u, 0x0u, false},
    {284u, "HitObject_PrimitiveIndex", "HitObject_StateScalar", "Shader Execution Reordering", "rn", "i", 6u, 9u, 0x0u, false},
    {285u, "HitObject_HitKind", "HitObject_StateScalar", "Shader Execution Reordering", "rn", "i", 6u, 9u, 0x0u, false},
    {286u, "HitObject_ShaderTableIndex", "HitObject_StateScalar", "Shader Execution Reordering", "rn", "i", 6u, 9u, 0x0u, false},
    {287u, "HitObject_SetShaderTableIndex", "HitObject_SetShaderTableIndex", "Shader Execution Reordering", "rn", "v", 6u, 9u, 0x0u, false},
    {288u, "HitObject_LoadLocalRootTableConstant", "HitObject_LoadLocalRootTableConstant", "Shader Execution Reordering", "ro", "v", 6u, 9u, 0x0u, false},
    {289u, "HitObject_Attributes", "HitObject_Attributes", "Shader Execution Reordering", "amo", "u", 6u, 9u, 0x0u, false},
    {290u, "ReservedB28", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {291u, "ReservedB29", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {292u, "ReservedB30", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {293u, "ReservedC0", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {294u, "ReservedC1", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {295u, "ReservedC2", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {296u, "ReservedC3", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {297u, "ReservedC4", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {298u, "ReservedC5", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {299u, "ReservedC6", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {300u, "ReservedC7", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {301u, "ReservedC8", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {302u, "ReservedC9", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {303u, "RawBufferVectorLoad", "RawBufferVectorLoad", "Resources", "ro", "hfwidl<hfwidl", 6u, 9u, 0x0u, false},
    {304u, "RawBufferVectorStore", "RawBufferVectorStore", "Resources", "", "hfwidl<hfwidl", 6u, 9u, 0x0u, false},
    {305u, "ReservedD0", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {306u, "ReservedD1", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {307u, "ReservedD2", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {308u, "ReservedD3", "Reserved", "", "", "v", 6u, 0u, 0x0u, true},
    {309u, "VectorReduceAnd", "VectorReduce", "Vector reduce to scalar", "rn", "<18wil", 6u, 0u, 0x0u, false},
    {310u, "VectorReduceOr", "VectorReduce", "Vector reduce to scalar", "rn", "<18wil", 6u, 0u, 0x0u, false},
    {311u, "FDot", "Dot", "Dot", "rn", "<hf", 6u, 0u, 0x0u, false},
};

static_assert(sizeof(kDxilOpcodeInfos) / sizeof(kDxilOpcodeInfos[0]) == 312);

} // namespace dxmt::dxil
