/*
 * Copyright (c) 2026 GameSir Labs and contributors
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 */

// Unit test: power-on D3DRS_* render-state default table.
// Expected values from Wine d3d9 conformance suite (dlls/d3d9/tests/stateblock.c).
// Omit driver-dependent states (POINTSIZE, POINTSIZE_MAX, DEBUGMONITORTOKEN).

#include "d3d9_state_defaults.hpp"

#include <bit>
#include <cstdio>

namespace {

int g_failures = 0;

DWORD
fl(float f) {
  return std::bit_cast<DWORD>(f);
}

struct RsCase {
  const char *name;
  D3DRENDERSTATETYPE state;
  DWORD expected;
};

// Verbatim from Wine stateblock.c render_state_default_data_init, in
// that function's order. (D3DRS_ZENABLE is checked separately below
// because its default depends on EnableAutoDepthStencil.)
const RsCase g_cases[] = {
    {"FILLMODE", D3DRS_FILLMODE, D3DFILL_SOLID},
    {"SHADEMODE", D3DRS_SHADEMODE, D3DSHADE_GOURAUD},
    {"ZWRITEENABLE", D3DRS_ZWRITEENABLE, TRUE},
    {"ALPHATESTENABLE", D3DRS_ALPHATESTENABLE, FALSE},
    {"LASTPIXEL", D3DRS_LASTPIXEL, TRUE},
    {"SRCBLEND", D3DRS_SRCBLEND, D3DBLEND_ONE},
    {"DESTBLEND", D3DRS_DESTBLEND, D3DBLEND_ZERO},
    {"CULLMODE", D3DRS_CULLMODE, D3DCULL_CCW},
    {"ZFUNC", D3DRS_ZFUNC, D3DCMP_LESSEQUAL},
    {"ALPHAREF", D3DRS_ALPHAREF, 0},
    {"ALPHAFUNC", D3DRS_ALPHAFUNC, D3DCMP_ALWAYS},
    {"DITHERENABLE", D3DRS_DITHERENABLE, FALSE},
    {"ALPHABLENDENABLE", D3DRS_ALPHABLENDENABLE, FALSE},
    {"FOGENABLE", D3DRS_FOGENABLE, FALSE},
    {"SPECULARENABLE", D3DRS_SPECULARENABLE, FALSE},
    {"FOGCOLOR", D3DRS_FOGCOLOR, 0},
    {"FOGTABLEMODE", D3DRS_FOGTABLEMODE, D3DFOG_NONE},
    {"FOGSTART", D3DRS_FOGSTART, fl(0.0f)},
    {"FOGEND", D3DRS_FOGEND, fl(1.0f)},
    {"FOGDENSITY", D3DRS_FOGDENSITY, fl(1.0f)},
    {"RANGEFOGENABLE", D3DRS_RANGEFOGENABLE, FALSE},
    {"STENCILENABLE", D3DRS_STENCILENABLE, FALSE},
    {"STENCILFAIL", D3DRS_STENCILFAIL, D3DSTENCILOP_KEEP},
    {"STENCILZFAIL", D3DRS_STENCILZFAIL, D3DSTENCILOP_KEEP},
    {"STENCILPASS", D3DRS_STENCILPASS, D3DSTENCILOP_KEEP},
    {"STENCILFUNC", D3DRS_STENCILFUNC, D3DCMP_ALWAYS},
    {"STENCILREF", D3DRS_STENCILREF, 0},
    {"STENCILMASK", D3DRS_STENCILMASK, 0xFFFFFFFF},
    {"STENCILWRITEMASK", D3DRS_STENCILWRITEMASK, 0xFFFFFFFF},
    {"TEXTUREFACTOR", D3DRS_TEXTUREFACTOR, 0xFFFFFFFF},
    {"WRAP0", D3DRS_WRAP0, 0},
    {"WRAP1", D3DRS_WRAP1, 0},
    {"WRAP2", D3DRS_WRAP2, 0},
    {"WRAP3", D3DRS_WRAP3, 0},
    {"WRAP4", D3DRS_WRAP4, 0},
    {"WRAP5", D3DRS_WRAP5, 0},
    {"WRAP6", D3DRS_WRAP6, 0},
    {"WRAP7", D3DRS_WRAP7, 0},
    {"CLIPPING", D3DRS_CLIPPING, TRUE},
    {"LIGHTING", D3DRS_LIGHTING, TRUE},
    {"AMBIENT", D3DRS_AMBIENT, 0},
    {"FOGVERTEXMODE", D3DRS_FOGVERTEXMODE, D3DFOG_NONE},
    {"COLORVERTEX", D3DRS_COLORVERTEX, TRUE},
    {"LOCALVIEWER", D3DRS_LOCALVIEWER, TRUE},
    {"NORMALIZENORMALS", D3DRS_NORMALIZENORMALS, FALSE},
    {"DIFFUSEMATERIALSOURCE", D3DRS_DIFFUSEMATERIALSOURCE, D3DMCS_COLOR1},
    {"SPECULARMATERIALSOURCE", D3DRS_SPECULARMATERIALSOURCE, D3DMCS_COLOR2},
    {"AMBIENTMATERIALSOURCE", D3DRS_AMBIENTMATERIALSOURCE, D3DMCS_MATERIAL},
    {"EMISSIVEMATERIALSOURCE", D3DRS_EMISSIVEMATERIALSOURCE, D3DMCS_MATERIAL},
    {"VERTEXBLEND", D3DRS_VERTEXBLEND, D3DVBF_DISABLE},
    {"CLIPPLANEENABLE", D3DRS_CLIPPLANEENABLE, 0},
    {"POINTSIZE_MIN", D3DRS_POINTSIZE_MIN, fl(1.0f)},
    {"POINTSPRITEENABLE", D3DRS_POINTSPRITEENABLE, FALSE},
    {"POINTSCALEENABLE", D3DRS_POINTSCALEENABLE, FALSE},
    {"POINTSCALE_A", D3DRS_POINTSCALE_A, fl(1.0f)},
    {"POINTSCALE_B", D3DRS_POINTSCALE_B, fl(0.0f)},
    {"POINTSCALE_C", D3DRS_POINTSCALE_C, fl(0.0f)},
    {"MULTISAMPLEANTIALIAS", D3DRS_MULTISAMPLEANTIALIAS, TRUE},
    {"MULTISAMPLEMASK", D3DRS_MULTISAMPLEMASK, 0xFFFFFFFF},
    {"PATCHEDGESTYLE", D3DRS_PATCHEDGESTYLE, D3DPATCHEDGE_DISCRETE},
    {"INDEXEDVERTEXBLENDENABLE", D3DRS_INDEXEDVERTEXBLENDENABLE, FALSE},
    {"COLORWRITEENABLE", D3DRS_COLORWRITEENABLE, 0x0000000F},
    {"TWEENFACTOR", D3DRS_TWEENFACTOR, fl(0.0f)},
    {"BLENDOP", D3DRS_BLENDOP, D3DBLENDOP_ADD},
    {"POSITIONDEGREE", D3DRS_POSITIONDEGREE, D3DDEGREE_CUBIC},
    {"NORMALDEGREE", D3DRS_NORMALDEGREE, D3DDEGREE_LINEAR},
    {"SCISSORTESTENABLE", D3DRS_SCISSORTESTENABLE, FALSE},
    {"SLOPESCALEDEPTHBIAS", D3DRS_SLOPESCALEDEPTHBIAS, fl(0.0f)},
    {"ANTIALIASEDLINEENABLE", D3DRS_ANTIALIASEDLINEENABLE, FALSE},
    {"MINTESSELLATIONLEVEL", D3DRS_MINTESSELLATIONLEVEL, fl(1.0f)},
    {"MAXTESSELLATIONLEVEL", D3DRS_MAXTESSELLATIONLEVEL, fl(1.0f)},
    {"ADAPTIVETESS_X", D3DRS_ADAPTIVETESS_X, fl(0.0f)},
    {"ADAPTIVETESS_Y", D3DRS_ADAPTIVETESS_Y, fl(0.0f)},
    {"ADAPTIVETESS_Z", D3DRS_ADAPTIVETESS_Z, fl(1.0f)},
    {"ADAPTIVETESS_W", D3DRS_ADAPTIVETESS_W, fl(0.0f)},
    {"ENABLEADAPTIVETESSELLATION", D3DRS_ENABLEADAPTIVETESSELLATION, FALSE},
    {"TWOSIDEDSTENCILMODE", D3DRS_TWOSIDEDSTENCILMODE, FALSE},
    {"CCW_STENCILFAIL", D3DRS_CCW_STENCILFAIL, D3DSTENCILOP_KEEP},
    {"CCW_STENCILZFAIL", D3DRS_CCW_STENCILZFAIL, D3DSTENCILOP_KEEP},
    {"CCW_STENCILPASS", D3DRS_CCW_STENCILPASS, D3DSTENCILOP_KEEP},
    {"CCW_STENCILFUNC", D3DRS_CCW_STENCILFUNC, D3DCMP_ALWAYS},
    {"COLORWRITEENABLE1", D3DRS_COLORWRITEENABLE1, 0x0000000F},
    {"COLORWRITEENABLE2", D3DRS_COLORWRITEENABLE2, 0x0000000F},
    {"COLORWRITEENABLE3", D3DRS_COLORWRITEENABLE3, 0x0000000F},
    {"BLENDFACTOR", D3DRS_BLENDFACTOR, 0xFFFFFFFF},
    {"SRGBWRITEENABLE", D3DRS_SRGBWRITEENABLE, 0},
    {"DEPTHBIAS", D3DRS_DEPTHBIAS, fl(0.0f)},
    {"WRAP8", D3DRS_WRAP8, 0},
    {"WRAP9", D3DRS_WRAP9, 0},
    {"WRAP10", D3DRS_WRAP10, 0},
    {"WRAP11", D3DRS_WRAP11, 0},
    {"WRAP12", D3DRS_WRAP12, 0},
    {"WRAP13", D3DRS_WRAP13, 0},
    {"WRAP14", D3DRS_WRAP14, 0},
    {"WRAP15", D3DRS_WRAP15, 0},
};

void
check_one(const DWORD (&rs)[256], const char *name, DWORD state, DWORD expected) {
  if (rs[state] == expected) {
    return;
  }
  ++g_failures;
  printf("not ok - D3DRS_%-26s expected %#010x, got %#010x\n", name, expected, rs[state]);
}

void
run(bool enable_auto_ds) {
  DWORD rs[256] = {};
  dxmt::init_default_render_states(rs, enable_auto_ds);

  // ZENABLE is the one default that varies with the implicit depth buffer.
  const DWORD want_zenable = enable_auto_ds ? D3DZB_TRUE : D3DZB_FALSE;
  check_one(rs, "ZENABLE", D3DRS_ZENABLE, want_zenable);

  for (const RsCase &c : g_cases)
    check_one(rs, c.name, c.state, c.expected);
}

} // namespace

int
main() {
  run(/*enable_auto_ds=*/true);
  run(/*enable_auto_ds=*/false);

  const size_t n = sizeof(g_cases) / sizeof(g_cases[0]) + 1; // +1 for ZENABLE
  printf("%zu state(s) x2 auto-DS modes, %d failure(s)\n", n, g_failures);
  return g_failures ? 1 : 0;
}
