/*
 * In vkd3d's own tree this header is generated by widl from
 * include/vkd3d_d3dcommon.idl. For a Windows/PE cross build the mingw-w64
 * SDK already ships the identical D3DCOMMON declarations, so redirect to it
 * rather than dragging the idl (and its d3d10 dependency chain) into the
 * vendored corpus.
 */
#include <d3dcommon.h>
